src/pipelines_repository/adf-build/generate_params.py
#22 
Allows for the **resolve:** keyword to be extended to support **resolve:region:/path/to/param**
If you wish to resolve parameters in the default deployment region you can use `resolve:/path/to/param` or if you wish to resolve from a different region within the deployment account you can pass `resolve:eu-west-1:/path/to/param` _(eu-west-1 being the example)_
=> v0.2.4 - resolving issue #22

docs/admin-guide.md, src/bootstrap_repository/adf-build/shared/python/stepfunctions.py, src/bootstrap_repository/deployment/global.yml, src/initial/lambda_codebase/account_bootstrap.py, src/initial/lambda_codebase/deployment_account_config.py, src/initial/lambda_codebase/determine_event.py, src/initial/lambda_codebase/event.py, src/initial/lambda_codebase/generic_account_config.py, src/initial/lambda_codebase/tests/test_event.py, src/initial/lambda_codebase/wait_until_complete.py, src/initial/template.yml
Adding in more detailed error handling for bootstrapping process. Allows for notifications to be sent on failures of bootstrapping stacks and splits up the state machine (in root and deployment account) to be more straight forward and have a more accurate and readable flow.
=> Adding in an error handling path for bootstrapping base stacks

src/bootstrap_repository/deployment/lambda_codebase/slack.py, src/bootstrap_repository/deployment/lambda_codebase/tests/stubs/slack.py, src/bootstrap_repository/deployment/lambda_codebase/tests/test_slack.py, src/initial/lambda_codebase/wait_until_complete.py
Updating the slack notification component to send notifications to slack correct on failed bootstrapping of accounts.
=> Updating Slack notification to send error for failing bootstrap stacks

requirements.txt, src/bootstrap_repository/adf-build/requirements.txt, src/pipelines_repository/adf-build/requirements.txt
fix reqs security alert -> 2.10.1, str.format_map allows a sandbox escape.
=> fix reqs security alert -> jinja2 2.10.1

src/pipelines_repository/adf-build/generate_pipelines.py, src/pipelines_repository/pipeline_types/cc-buildonly.yml.j2
#27 Allowing a build only pipeline - This PR builds on #31
Allows for targets to be optional in the deployment map and returns an empty array from generate_pipelines if it is omitted. Creating a new pipeline type *cc-buildonly.yml.j2* (thanks @thiezn)
With this change you can now construct a pipeline like:
```
- name: my-build
type: cc-buildonly
params:
- SourceAccountId: 12345678910
```
If you wanted to access resources cross region you would do so in your code that is executed within CodeBuild.
=> Adding in a Build Only style pipeline

src/pipelines_repository/adf-build/deployment_map.py, src/pipelines_repository/adf-build/tests/stubs/stub_deployment_map.yml
#31 
Fixing slight issue with optional targets key in deployment_map
=> slight fix on deployment_map.py to allow empty targets

src/bootstrap_repository/adf-build/main.py, src/initial/lambda_codebase/account_bootstrap.py, src/initial/lambda_codebase/event.py
Fixing issue that was not adding 'cross_account_iam_role' to the deployment account when setting up ADF from scratch
=> fixing bug in event.py when setting up adf from scratch

docs/user-guide.md, src/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2, src/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
While trying out the `replace_on_failure` option I noticed that the current pipeline types do not support the `CAPABILITY_AUTO_EXPAND` capability which is required when creating a stack that contains Transforms such as SAM.
I have added this capability to both cloudformation pipeline types as well as including an example of the usage of `replace_on_failure` parameter into the user-guide.md file.
---
=> Fixing support for Transforms when using the replace_on_failure option

src/bootstrap_repository/deployment/global.yml
When working with more than 30 AWS Accounts in two regions the Lambda function on the Deployment Account *(EnableCrossAccountAccess)* can become slowed down as it updates/syncs policies across many accounts and regions and can ultimately timeout. This change takes it from 55 seconds execution time to 5 seconds.
=> Increasing the power and timeout of the EnableCrossAccount Lambda

docs/admin-guide.md
I have made a minor change to the docs to include a minimum version number for the AWS CLI. With older versions the cloudformation package and deploy commands fail due to the lack of Lambda layer support.
=> updated docs to include minimum AWS CLI version required

src/lambda_codebase/initial_commit/bootstrap_repository/deployment/global.yml
Add the `adf-codecommit-role` to the deployment account bootstrap template so that code repositories can also be stored in the deployment account. Currently the creation of pipelines fails when the codecommit repo is located in the deployment account.
deployment_map.yml:
```
pipelines:
- name: sample-vpc  # The name of your pipeline (This will match the name of your repository)
type: cc-cloudformation  # The pipeline_type you wish to use for this pipeline
params:
- SourceAccountId: 1111111111111  # The source account that will hold the codebase
pipeline
targets:  # Deployment stages
- /marketing/non-prod
```
Error in cloudformation template deployment:
```
arn:aws:iam::1111111111111:role/adf-codepipeline-role is not authorized to perform AssumeRole on role …
```
=> Add adf-codecommit-role to deployment account

src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/adf-build/deployment_map.py
*Issue #78:*
*Description of changes:* Added support for loading deployment_map files form a deployment_map dir.
The code loads deployment_map.yml then if there is a deployment_map dir and it has content it loads any yml files in there. The deployment_map/*.yml follow the exact same format as the deployment_map.yml. The loaded subfiles are merged with the pipelines list of the deployment_map.yml. If there was not deployment_map.yml it creates an empty pipelines array that it subsquently fills with content from subfiles. 
Example 1.
```
RihaDevTeam:~/environment/adf/deploy/aws-deployment-framework-pipelines (master) $ ls
adf-build  deployment_map  deployment_map.yml  pipeline_types  pytest.ini
RihaDevTeam:~/environment/adf/deploy/aws-deployment-framework-pipelines (master) $ …
```
=> Added support for sub deployment_map files

src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-customdeploy.yml.j2, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
*Issue #89*
*Description of changes:* Added a custom deployment template, cc-customdeploy. This creates a codebuild for each deploy stage. By default it uses the spec file deployspec.yml and the adf-cloudformation-deployment-role deployment role. But its possible to specify custom deploy spec and deploy role like this.
```
pipelines:
- name: example-app
type: cc-customdeploy
params:
- SourceAccountId: 01234567890
targets:
- path: 0987654321
params:
Specfile: deployspec-qa.yml
DeployRoleArn: arn:aws:iam::0987654321:role/example-app-deploy-role
- path: 8901234556
params:
Specfile: deployspec-prod.yml
DeployRoleArn: arn:aws:iam::8901234556:role/example-app-deploy-role
```
I also added the ability to create a custom deploy role to the other CF based pipe templates where it was used.
By …
=> Custom Deploy pipe template

src/lambda_codebase/initial_commit/bootstrap_repository/deployment/regional.yml
Fix: removed the duplicate DeletionPolicy Attribute in the initial commit for the regional deployment bucket, because it was taking precedence over the "Retain"
in src/lambda_codebase/initial_commit/bootstrap_repository/deployment/regional.yml
```
DeploymentFrameworkRegionalS3Bucket:
Type: AWS::S3::Bucket
DeletionPolicy: Retain <=== added in June to "v1.0.0" 368ec00 
Properties:
...
DeletionPolicy: Delete <=== added in March to the "initial commit" 095185f
```
Explanation: 
This CF template ends with status `DELETE_SKIPPED` after stack deletion:
```  
Resources:
DeploymentFrameworkRegionalS3Bucket:
Type: AWS::S3::Bucket
DeletionPolicy: Delete
DeletionPolicy: Retain
```
This CF template ends with status `DELETE_COMPLETE` after stack deletion:
```
Resources: …
```
=> Fix: removing the duplicate DeletionPolicy Attribute

src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
https://github.com/awslabs/aws-deployment-framework/issues/98
Added CAPABILITY_AUTO_EXPAND to change_set_replace action in cc-cloudformation and github-cloudformation pipeline types.
=> Added CAPABILITY_AUTO_EXPAND to github and codecommit pipeline templates

docs/user-guide.md
**Issue #, if available:** N/A
**Description of changes:** Fixed the Github example, the previous one listed a `SourceAccountId` which only applies to CodeCommit. It was also missing param's required for Github.
=> Fixing Github Example in User Guide

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
*Issue #, if available:* #116 
*Description of changes:* Updated github-cloudformation.yml.j2 to support a Repository name which is different from the Pipeline/Projectname. Also added minor change to user-guide to clarify changes. 
=> GitHub repo name support

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_pipelines.py
*Issue #, if available:* #119 
*Description of changes:* Instead of using the split name (see: https://github.com/awslabs/aws-deployment-framework/blob/master/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_pipelines.py#L49), use the full name of the SSM parameter when calling SSM delete_parameter.
=> Adding minor fix for SSM clean-up

src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-customdeploy.yml.j2
*Issue #, if available:* 142
*Description of changes:* remove doubled keyword ServiceRole in cc-customdeploy.yml.j2
=> bugfix #142 remove doubled keyword ServiceRole

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/package_transform.sh
This fixes the sam package command when it will try to access the bucket in the wrong region by specifying the region.
=> Proposed fix for issue #134

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_cloudformation.py
With this fix it replaces all unaccepted chars from the CloudFormation
(CFn) stack name with a dash.
For example, when the OU name would be 'IT Department', it would fail
setting up the base ADF resources as it would generate the following
stack name: 'adf-global-base-IT Department', which includes a space that
is not supported by CloudFormation.
With this fix, it will replace the space with a dash, the new name would
become: 'adf-global-base-IT-Department'. Any other unsupported character
is treated the same.
=> Fix to replace spaces and other unaccepted chars from CFn stack names

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/target.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_deployment_map.yml
**Issue:** #75
When the deployment map would refer to a specific AWS Account Id that
has a zero as the first digit, the number would be interpreted
differently or would not be accepted by validation at all.
For example, `012345678901` would become `12345678901` (zero removed),
and `012345671234` would become `1402434204` (interpreted as octal).
**Fix:**
In this commit, the schema validation for AWS Account Ids allows the use
of strings to define the account id. Such that an account id that has a
zero at the start would not be changed.
Additionally, the logic has been changed to detect AWS Account Ids that
do not match the AWS Account Id regular expression. In case this
happens, the error message will instruct the user to define the account
id in a string. It will also show how the account …
=> Fix for AWS Account Ids prefixed with zeroes

samples/sample-mono-repo/README.md, samples/sample-mono-repo/apps/alpha/README.md, samples/sample-mono-repo/apps/alpha/buildspec.yml, samples/sample-mono-repo/apps/alpha/params/global.yml, samples/sample-mono-repo/apps/alpha/template.yml, samples/sample-mono-repo/apps/beta/README.md, samples/sample-mono-repo/apps/beta/buildspec.yml, samples/sample-mono-repo/apps/beta/params/global.yml, samples/sample-mono-repo/apps/beta/template.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_deployment_map.yml
Adds the `root_dir` property to the `cloudformation` deployment
provider properties. This enables the user to define multiple pipelines
that target the same repository, where each application/pipeline could
use different directories to host the CloudFormation template and
parameters.
In terms of CodeBuild: make sure to `cd` into the correct directory as
shown in the mono-repo sample. This is required to generate the
parameter files in the correct directory as well.
No changes were required for CodeBuild mono-repo support, as you can
specify the location of the BuildSpec using the `spec_filename` property
of the `codebuild` provider properties.
**R0915:**
A note on the added `pylint: disable R0915`: intentionally the modifications
required to add mono repo support touch as little as …
=> Mono repo support

docs/types-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_cloudformation.py
* Added root_dir to the CloudFormation deployment definition in the
Types Guide documentation.
* Fixed small typo of floating `s` after a period in Types Guide.
* Removed unnecessary import as discussed in #156.
=> Added root_dir attribute of CloudFormation to Types Guide

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/main.py
*Note: Please merge #169 first. This PR builds upon that commit.*
Use pipeline name for CodeBuild instead of target name
**Issue:**
Currently, the name of the CodeBuild project is determined based on the
name of the target it points too. In the case of CodeBuild this would
always be the name of the deployment account.
Having multiple pipelines that have a CodeBuild project with the same
stage index would clash though.
**Fix:**
Use the name of the pipeline for CodeBuild instead of the target name,
as it will always operate from the deployment account.
Moved CodeBuild deployment action outside of region loop
**Issue:**
In the current format, one could think that CodeBuild supports being
deployed in a specific target region while this is not supported.
As written in #168, the name of the …
=> Fixes CodeBuild unique project name for deployment stages

Makefile, requirements.txt, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/tests/__init__.py, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/tests/test_initial_commit.py, src/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/pytest.ini, src/lambda_codebase/initial_commit/requirements.txt, src/lambda_codebase/initial_commit/tests/__init__.py, src/lambda_codebase/initial_commit/tests/test_initial_commit.py, tox.ini
**Issue:**
When upgrading ADF, it deletes the old files that have been removed
between versions. However, the way it performs this test contained an
issue where it deleted the `deployment_maps` directory and other json/yaml
files that were not specifically whitelisted to be kept.
**Fix:**
Checks the files that would be scheduled for deletion against a regular
expression. When the file ends with a `json`, `yaml`, `yml` file extension
it should be kept in the repo as is.
Unit tests have been added to ensure that it would work as intended.
=> Fix to skip deletion of deployment_maps dir and other json/yaml files

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
**Issue:**
When using CodeBuild for both deployment steps and integration tests, you would want to be able to specify the use of a specific `spec_filename` as shown in the third target stage below (named `integration-tests`).
```yaml
pipelines:
- name: deploy-using-codebuild-pipeline
default_providers:
source:
provider: codecommit
properties:
account_id: 111111111111
build:
provider: codebuild
properties:
image: STANDARD_2_0
deploy:
provider: codebuild
properties:
image: STANDARD_2_0
spec_filename: different_deployspec.yml
targets:
- name: deploy-to-dev
provider: codebuild
properties:
environment_variables:
BUCKET_NAME: some-bucket-to-use-in-dev
- name: deploy-to-test
provider: codebuild
properties:
environment_variables:
BUCKET_NAME: some-bucket-to-use-in-test
- name: integration-tests …
```
=> Fixes use of target spec_filename over default for CodeBuild deployments

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
#186 Explicitly defined stack_name in default_providers section is ignored
use default_providers:deploy:properties:stack_name if defined
=> use default_providers:deploy:properties:stack_name if defined

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
#202 Pipeline with S3 as Deployment Provider fails with error
use target account for roleArn instead of code-source account for S3 deployment provider 
=> use target account for roleArn instead of code-source account

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/retrieve_organization_accounts.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt, src/lambda_codebase/initial_commit/bootstrap_repository/deployment/global.yml
AWS Account details of the member accounts in the organization are
required for services like AWS Security Hub and Amazon GuardDuty.
This helper script will allow you to retrieve all the member account
details of the accounts in the organization as part of the CodeBuild
step. The member account details will be written to a JSON file on the
path as specified during execution.
For example, to get the account details required for AWS Security Hub
to send the invites correctly, you would need to execute the script
with the following arguments to fetch the details:
```bash
python adf-build/helpers/retrieve_organization_accounts.py -v \
-o src/custom_resource/invite_members/member_accounts.json \
-f Id \
-f Email
```
This will write the JSON file directly inside the code base of the …
=> Add Retrieve Organization Accounts helper

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/package_transform.sh
**Why:**
The AWS Serverless Application Model (SAM) build action tries to fetch
all requirements specified in the `requirements.txt`.
However, this does not work when you would like to use other sources to
host the python modules than the default public one.
**How:**
In order to skip the `sam build` step, specify the `--no-build` flag to
the `package_transform.sh` script.
=> Add ability to skip SAM build in package-transform

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt
In the current release of ADF, the `shared/requirements.txt`
automatically includes three CDK modules with the latest version.
This commit will version-lock those modules to version `1.20` like all
other modules, such that it will not run into compatibility issues when
new versions of CDK are released.
The missing dependencies were:
- `aws-cdk.aws-sam`
- `aws-cdk.cx-api`
- `aws-cdk.region-info`
**References:**
- Fixes #223 (CodeBuild failure: Newer version of CDK is required issue)
=> Version lock missing CDK dependencies

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
The `adf-build/helpers/package_transform.sh` helper is not able to
operate without rights to perform `ssm:GetParameters`.
This commit will add it to the `adf-codebuild-role` in the `/deployment` OU.
=> Fix IAM for package transform helper to function

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
The `adf-build/helpers/retrieve_organization_accounts.py` script will need
to determine which organization it belongs to.
It performs this operation using the [organizations:DescribeOrganization](https://docs.aws.amazon.com/organizations/latest/APIReference/API_DescribeOrganization.html)
API call from inside CodeBuild in the deployment account.
In order for this to be successful, the deployment account needs to
grant CodeBuild access to this operation. This change will add that
to the policy of CodeBuild.
=> Fix IAM for retrieve organization accounts helper

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/s3.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_s3.py
In order to reference files from CloudFormation, like a Swagger
OpenAPI definition, you need to use the `s3://` format.
At the moment, the `upload:` helper is able to return `path` or
`virtual-hosted` urls. With this PR, it will get support to return
S3-URIs as well.
Modifications:
- Added S3-URI syntax support.
- Removed redundant code for `path` and `virtual-hosted`.
- Added tests to verify the styles and different region configs.
- Documentation has been updated to clearly distinguish the different
output styles.
**References:**
- Fixes #197 (requests `s3://` as an output format for `upload:` helper).
=> Add S3-URI as upload path style

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
**In short:**
The `aws:SourceArn` condition is missing in the STS Assume Role context.
This prevents the `generate_params.py` script from assuming into
accounts to get the parameters and outputs from the target accounts.
**In more detail:**
Context when it runs `generate_params.py`:
* CodeBuild will be operating on STS credentials that it gathered when
the service assumed into the `adf-codebuild-role` in the Deployment
account.
* When executing the `adf-build/generate_params.py` script, it will perform
an STS Assume Role operation into the `adf-readonly-automation-role` in the
target accounts that it needs to fetch parameters or outputs from.
As the latter operation is using an IAM Role to assume into another IAM Role,
we cannot use the `aws:SourceArn` condition as that is no longer …
=> Fix CodeBuild assume role to generate parameters

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py
In the code and docs of the import statement, it was referring to the
`export_key`. However, in the fine print it stated that it is referring
to the `output_key` as part of the Stack outputs instead.
This was confusing people to create outputs with export ids, thinking
they had to. This update renames the usage to `output_key` instead such
that it is consistent in the docs and code.
=> Fix import references of export to output key

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/s3.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_s3.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py
No issue available
Added a new Upload style called `aws-key-only`. This is very similar to `s3-uri`, but it only returns the Key value.
It's very useful in case you need to use CDK to declare a Lambda Function and want to use the `fromBucket` method for the source code. 
Since you can't use CDK `fromAsset` method with ADF, then you would have to find another way to upload your Lambda code using a native method like ADF Upload. `fromBucket` method  asks for Bucket Name and S3 Key to be provided, but you can't know those before running the ADF Build stage, so you need to find a way to declare this values using CloudFormation Parameters. Since `s3-uri` returns a String similar to `<bucketName>/adf-upload/<assetFolder>/<asset>` and that's …
=> Adds s3-key-only style

Makefile, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_events.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_github.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_notifications.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/__init__.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codebuild_determine_build_image.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/pytest.ini, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/pytest.ini, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt, tox.ini
**Issue:**
When one would try to specify the CodeBuild image in the target
environment when using CodeBuild, it did not accept having strings
as input.
For example, with this deployment map:
```yaml
- name: sample-pipeline
default_providers:
source:
provider: codecommit
properties:
account_id: 111111111111
build:
provider: codebuild
properties:
image: STANDARD_3_0
deploy:
provider: cloudformation
targets:
- name: deploy-to-dev
path: /development
- name: integration-tests-on-dev
provider: codebuild
properties:
image: STANDARD_3_0
spec_filename: testspec.yml
```
This would fail with the following error:
```
jsii.errors.JSIIError: Expected object reference, got "STANDARD_3_0"
Subprocess exited with error 1
```
It was only able to handle ECR dictionary image types before.
**Fix:**
Refactored …
=> Fix CodeBuild use specific image in target stage

docs/user-guide.md
*Issue #, if available:* Removing Pipelines anchor was pointing to the wrong subheading
*Description of changes:* Updated the anchor to point to the Removing Pipelines section
=> Correct removing pipelines anchor

requirements.txt
With the release of isort v5 the builds of our main branch kept failing.
Travis CI was using the latest version as it was not instructed to do
otherwise.
With this release, we force it to install v4 instead so builds continue to
operate until they support isort v5 in pylint.
=> Use isort v4

docs/user-guide.md
The documentation incorrectly referred to the `spec_inline` attribute as
`inline_spec`. As can be seen in [0], the correct attribute name is
`spec_inline`.
* [0] [src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py#L91-L93](https://github.com/awslabs/aws-deployment-framework/blob/385c0e4832437f42e5eb4607ddc3c99b529ac3d4/src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py#L91-L93)
=> Fix spec_inline attribute of CodeBuild in docs

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/clean_pipelines.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py
Added a new python script for removing stale entries from SSM and
deleting cloudformation templates for pipelines no longer defined
in the deployment map(s)
This script is called in the post_build stage of the pipeline
generation CodeBuild project.
=> Seperated out pipeline cleanup from input generation

Makefile, src/lambda_codebase/account/main.py, src/lambda_codebase/account/pytest.ini, src/lambda_codebase/account/tests/__init__.py, src/lambda_codebase/account/tests/test_main.py, tox.ini
**Why?**
When the account creation failed due to a concurrency failure, it would
retry creating the account. However, since the retry was not returned,
the created account would be ignored and the original invocation would
fail with `UnboundLocalError: local variable 'create_account' referenced
before assignment`.
**What is changed?**
The logic to create the account is separated into separate functions to
support testing the code segments. Tests have been written to simulate
the situation that failed before. Since no tests were written for this
custom resource yet, the other code that was part of the ensure_account
function got tests to ensure their operation too.
This fixes #280.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> Fix #280 - create deployment account concurrency failure

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
**Why?**
A bug prevented stages like Approvals to be included in a pipeline. As
the _generate_role_arn function tried to retrieve the specific role for
the approval stage, while that stage doesn't support such properties.
**What changed?**
Added a check to look for specific roles in Build and Deploy stages
only. All other stages should not use a specific role.
=> Fix specific role usage to be used in Build and Deploy only

src/template.yml
v3.1.0 release notes:
**Features 🏗**
* Adds Enterprise Support to account creation process #233, closes #232:
* ADF will raise a ticket to add the account to an existing AWS support subscription when an account is created. As a prerequisite, your organization master account must already have enterprise support activated.
* Adds nested deployment map support #266 and #328, closes #265:
* This enables usage of sub directories within the deployment_maps folder.
**Fixes 🐞**
* Fixes specific role usage to be used in Build and Deploy only #295.
* Corrects removing pipelines anchor in docs #279.
* Fixes CI builds due to isort version mismatch #284.
* Fixes error handling of generate_params intrinsic upload function #277, closes #276.
* Fixes spec_inline attribute of CodeBuild in docs #289.
* …
=> Release v3.1.0

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_params.py
**Why?**
As reported by issue #147, the leaf parameter files that specify the parameters/tags for
the account region environment did not work.
**What?**
The account_region parameter was not processed properly.
=> Fix intrinsic functions for account_region param files

samples/sample-etl-pipeline/README.md, samples/sample-etl-pipeline/scripts/some_etl_script.sh, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/adf_codepipeline_test_constants.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codepipeline_generate.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codepipeline_input_artifacts.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codepipeline_output_artifacts.py
When the build stage is disabled, the deploy stages incorrectly tried to use the build output artifact.
These should use the source artifact instead.
* #236
* #318
=> Fix usage of source artifacts in deploy stages when build stage is disabled

src/template.yml
**Fixes 🐞**
* Fixes `timeout` and `environment_variables` to be used when defined in
the default CodeBuild Deployment provider properties #307, closes #306.
* Fixes intrinsic functions for account_region param files #333, closes #147.
* Fixes use of deployment from source directly when build stage is
disabled #334, closes #236 and closes #318.
=> Release v3.1.1

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_params.py
**Why?**
A bug prevented the use of the `resolve:` intrinsic function on the first parameter in in the first parameter file.
**What?**
The parameters were initialized as an empty dictionary. While reading a file that does not exist would return a predefined object instead. The fix uses the later instead of an empty dictionary.
=> Fix resolve intrinsic function use in first parameter

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/requirements.txt, src/lambda_codebase/initial_commit/requirements.txt
**Why?**
A vulnerability was reported on v2.11.2 of Jinja2, as reported per
CVE-2020-28493. Since we make use of this dependency, we need to link to
the version that resolved this issue.
Since ADF does not use the `urlize` that is impacted, it is not at risk.
Hence it is not required to release a new version or update your ADF
installation.
**What?**
Updated to 2.11.3.
=> Update Jinja2 to v2.11.3

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py
We are running into this with an OU that has a `.` in the name.
I used the constraints found on https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html 
=> Reject more characters from a CloudFormation Stack name

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
This allows users to define anchors in one place.
ADF already encourages anchors in the documentation, this should make them even more convenient.
I added an example in the user guide to document this feature.
=> Allow top-level keys starting with x- or x_ in deployment maps

docs/providers-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_events.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_github.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/adf_default_pipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py
For several use cases, it would be great to have a pipeline that would not trigger on source updates.
For example, a pipeline might only need to be triggered on a schedule, by the completion of another pipeline, or manually.
This was requested by the following issues:
* Issue #308 - Starting pipeline only on completion_trigger
* Issue #337 - Question: Disable webhook for Github provider
The CodeCommit, Github, and S3 source providers have been update to support disabling triggering on source changes.
As described in the `docs/providers-guide.md` documentation, you can optionally disable it when required.
This code also solves a bug when a pipeline would rely on polling of changes for CodeCommit. In the previous version, it would be triggering twice instead of once when the source account …
=> Add ability to disable trigger on changes for S3/CC/GH source providers

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/provisioner/src/support.py, src/template.yml
**Why?**
As reported in #379, the IAM permission required to enable Support Subscriptions upon account creation is missing.
**What?**
This change adds another Role that is used by the Bootstrap CodeBuild project to request the right support level upon account creation.
A separate role is required, as the permissions should not be added to the default ADF CodeBuild role that is also used by the pipelines generated by ADF.
---
=> Fix permission to set Support Subscription upon account creation

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
Step function incorrectly referenced the lambda function, rather than the map operator
=> Fix: Incorrect step name in step function.

docs/admin-guide.md, src/template.yml
When you run into errors deploying the latest version of ADF, it was not easy to enable the debug level, as those used to be hard coded and non-configurable.
Additionally, the admin guide does not provide the required information to trace issues independently.
This change introduces a Log Level parameter to the SAR deployment process.
Allowing the administrators to deploy ADF with a specific Log Level such as DEBUG directly from the SAR.
It also explains how to troubleshoot ADF deployments to the admin guide.
---
=> Feature enable setting the log level on deploy + troubleshoot ADF guide

src/template.yml
In one of our recent PRs the indentation of the state machine was
changed. However, with this update, it seems that part of the state
machine got copied.
Because of this, Step Function was unable to deploy/update the state
machine.
Removed the redundant parts of the state machine.
I checked both definitions, the repeated segments are a 1:1 copy.
---
=> Fix duplicated steps in Account Bootstrap Step Function

src/lambda_codebase/account_processing/get_account_regions.py
*Issue #, if available:* #420 
Updated the get_account_regions function to use the opted-in value in the region filter. 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_regions 
=> Updating get account region function to use opted-in regions too

docs/admin-guide.md, docs/providers-guide.md
**Why?**
The docs stated that the default branch would always default to `master`
when the branch is not specified.
However, the branch that is used is determined by looking up the
`config/scm/default-scm-branch` as configured in the `adfconfig.yml` file.
**What?**
Updated the docs accordingly.
---
=> Update docs to state the default branch used as the source

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/example-global-iam.yml
**Why?**
At the moment, the `global-iam.yml` is stating that it is deployed to the deployment account. However, this specific file is deployed to all target accounts instead.
**What?**
Simple, updated the comment.
---
=> Fix global-iam example comment explaining where it is deployed

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_notifications.py
*Issue #, if available:* #422
Because ADF already has a KMS key that is used for encryption. It makes sense to use that key for the SNS notifications as well.
=> feat: encrypt sns topic using the ADF CMK KMS Key

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
*Issue #, if available:* #447
Older buckets have set the object ownership set to `Object writer`. Newer buckets deviate from this behavior causing permission issues in the deployment pipelines.
=> fix: object ownership controls

.cfnlintrc, Makefile, requirements.txt, samples/sample-ec2-with-codedeploy/template.yml, samples/sample-ecs-cluster/template.yml, samples/sample-serverless-app/template.yml, src/account_processing.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/regional.yml, src/template.yml
#464
- Implementing cfn-lint. 
- Minor changes to a few templates to satisfy cfn-lint rules.
**Note:** this is NOT added to CI (travis), after this commit and the `yamllint` is accepted I can work on integrating with CI. 
=> Feat 464: Implement cfn-lint

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/enable_cross_account_access.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/iam.py
*Issue #, if available:* #474
[Broken down in the gist here](https://gist.github.com/StewartW/aff84e6f86811b128ca03b4d2014f559)
Separates out the policies for cloudformation-role in the target accounts and codepipeline role in the deployment account. 
Now have policies for S3, KMS and a base policy that catches everything else. 
Updated the shared IAM library to take in a list of policies to update now, also accepts single string and will treat it accordingly. 
Existing update policy code also provides backward compatibility because it checks if the statement with the SID exists in the policy and if it can't find it - it does nothing. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
=> Fix: #474 Generated Policy Size Too Long

.editorconfig, .yamllint, src/template.yml
**Why?**
With editorconfig, editors that are used across our collaborators will be able to use the same indentation / line lengths and other configuration settings.
You can find more information on how to install the editorconfig add-on for your editor on: https://editorconfig.org/
**What?**
* Adding specification as currently applied in the files in our repository.
* Minor updates to match line length and trailing space config.
---
=> Chore: Add editorconfig to repo

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/partition.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_partition.py
**Why?**
At the moment, the organization API calls are made to the region where the `organizations.py` code is running.
However, which region to use depends on the partition that is in use.
For the US gov-cloud regions, it should use the `us-gov-west-1` region.
While the `aws` partition regions should use `us-east-1`.
**What?**
The code will determine the partition and return the correct region to use for the Organizations API.
---
=> Fix: Lookup correct Organization API Region

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/repo.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/schema_validation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/templates/codecommit.yml
*Issue #, if available:* #468
When a pipeline description is given it was already propagated to the CodeCommit repository. Only the schema did not allow to provide the description, and the IAM policy contained an invalid action and did not allow description updates.
=> feat: use default description as CodeCommit repository description

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
Issue: #488.
**What?**
Updated references and made sure line length would not exceed the maximum on
the lines that were changed.
---
=> Fix incorrect CodeBuild build/deploy references in params

.mega-linter.yml, samples/sample-rdk-rules/buildspec.yml, samples/sample-rdk-rules/config-rules/EC2_CHECKS_TERMINIATION_PROTECTION_ADF/parameters.json, samples/sample-rdk-rules/templates/lambda-function.json, samples/sample-rdk-rules/templates/lambda-permission.json, samples/sample-rdk-rules/templates/lambda-role.json, samples/sample-rdk-rules/templates/parameters.json, samples/sample-rdk-rules/templates/skeleton.json
N/A
This PR makes style adjustments that do not satisfy our linters. Unfortunately the `rdk` samples PR merge crossed the merge of the linter, hence they where not caught. Specifically this rule:
https://github.com/awslabs/aws-deployment-framework/blob/master/.editorconfig#L30-L31
Also added: 
```yaml
CLOUDFORMATION_CFN_LINT_FILE_EXTENSIONS: [".yml", ".yaml"]
```
To the linter config to bring it inline with our `cfn-lint` configuration. This repo doesn't have `json` CloudFormation templates, but the `rdk` samples have partial templates in `json` that are otherwise incorrectly flagged.
=> fixing linter issues introduced by rdk examples

Makefile
**Issue:** #473
**What?**
Fixed as suggested by @javydekoning in the original issue.
Personally I did not experience this issue on my machine, but removing the trailing slash wouldn't hurt either way.
---
=> Fix find command on macOS, removing trailing slash in Makefile

docs/providers-guide.md, samples/sample-rdk-rules/templates/lambda-role.json, src/lambda_codebase/account_processing/configure_account_alias.py, src/lambda_codebase/account_processing/delete_default_vpc.py, src/lambda_codebase/account_processing/get_account_regions.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_chatbot.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/sts.sh, src/template.yml
**Why?**
Some of the pull requests might have overlapped with the pull request that introduced support for the `aws-us-gov` partition.
By searching for `:aws:`, I found a number of references that were still hard coding the `aws` partition.
**What?**
Adding support for dynamic partitions where it was not supported yet.
---
=> Fix correct use of partitions

docs/user-guide.md, samples/sample-cdk-app/buildspec.yml, samples/sample-rdk-rules/buildspec.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
**Why?**
Unfortunately `STANDARD_5_0` does not support the latest LTS v16 of NodeJS.
**What?**
NodeJS v14 is supported, changed accordingly.
---
=> Use NodeJS 14 with CodeBuild STANDARD_5_0

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codebuild_determine_build_image.py
**Issue:** #382
**Why?**
As reported by #382, setting a specific container image to use by the
CodeBuild provider to deploy to a target resulted in an error.
The CDK stack would fail to synthesize as the 'custom_repo' resource
name was already present in the stack.
**What?**
This fix ensures a unique identifier is used for custom container repositories.
---
=> Fix use of separate container image per target

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/requirements.txt
**Why?**
With the pipeline generator PR, it seems that the version number was incorrectly
copied over. Instead of 1.14.1 it was specified as 1.41.1, which does not exist.
**What?**
Changing the version to 1.14.1.
---
=> Fix wrapt version dependency

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
**Why?**
When it tried to sync a deployment_map.yml file that did not exist in the
pipelines repo, it would fail with exit code 1.
Additionally, the files directly inside the deployment_maps folder were not
synced, only nested folders were synced correctly.
**What?**
* Moved install commands to the install phase in the CodeBuild buildspec.
* Added a check to test whether the folder/file exists before syncing.
* Added echo messages to explain what and why it does or doesn't sync.
* Added or statement to ensure that it will succeed with exit 0 when
files/folders are missing.
---
=> Fix syncing deployment_map files to s3

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/identify_out_of_date_pipelines.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
At the moment, the InvokeDeleteStateMachine task is called even when no pipelines need to be deleted. This causes the actual state machine that deletes these tasks to fail. As it cannot iterate over an empty list.
Introducing a choice, that will only invoke the delete pipelines state machine when there is a need to do so.
---
=> Improvement: Only invoke pipeline deletion when needed

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml
The Generate Pipeline Input lambda function tried to assume into the cross-account access role, to read the organization API.
This was not allowed, as it was not permitted by the cross-account access role as a trusted role that can assume into the read-only role in the management account.
Addressed by adding a specific role name for the role that is used by the Generate Input lambda function. Plus putting that role on the allowed list of roles that are allowed to assume the cross-account access role for read-only access to the organization API.
---
=> Add missing permission to assume Cross-Account-Org R/O role

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
After updating the CloudFormation template for a ADF pipeline, it tries to update the termination protection flag on the stack. This will fail as the permissions are not configured yet. The failure it returned was:
> 2022-08-30 14:22:24,295 | ERROR | cloudformation | 111111111111 | adf-pipeline-some-pipeline, Error: An error occurred (AccessDenied) when calling the UpdateTerminationProtection operation: User: arn:aws:sts::111111111111:assumed-role/adf-global-base-deploymen-PipelineManagementCodeBu-xxxxxxxxxxxxx/AWSCodeBuild-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is not authorized to perform: cloudformation:UpdateTerminationProtection on resource: arn:aws:cloudformation:eu-west-1:111111111111:stack/adf-pipeline-some-pipeline/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx because no identity-based …
=> Fix permission to update termination protection on pipeline stacks

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
**Why?**
In the past, the ADF Pipelines were updated from the CodeBuild step in the `aws-deployment-framework-pipelines` CodePipeline flow.
With the recent release of the Step Function Pipeline Management State Machine, this logic has moved.
To ensure that administrators still understand what happens and whether the pipelines are updated correctly, we should link them to the state machine from the CodeBuild execution.
**What?**
Doing exactly that, adding a reference to the state machine in the CodeBuild step.
---
=> Add reference to state machine from CodeBuild on pipeline updates

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/requirements.txt, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/template.yml
In PR #513, an error was introduced which broke the syntax of the State Machine definition.
While investigating, I discovered a number of other improvements that might help, addressing these in this change.
* Fixing missing and redundant commas in retry logic.
* Moving roles and other properties of State Machines to the beginning, so they
don't float around at the end of the state machine definition.
* Enabled tracing on state machines.
* Updated name of Account Bootstrapping state machine.
---
=> Fix ADF State Machines

src/lambda_codebase/account_processing/configure_account_alias.py, src/lambda_codebase/account_processing/tests/test_account_alias.py, src/template.yml
At the moment, the account management state machine will attempt to add the specified alias to the account whether it is present or not.
In case the alias already exists, it will fail.
This change will ensure the aliases configured on the account are removed when they are no longer configured (you can only have one, but the API supports multiple). It will then add the alias if the alias that needs to be present is
missing.
Updated maximum number of attempts in the State Machines to max 10, as 30 would imply multiple days of retries.
---
=> Fix updating account alias when needed

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/requirements.txt
A typo slipped into the main branch, where it tries to install `tenacity=8.0.1`.
It should be `==`.
---
=> Fix pip requirements typo

docs/providers-guide.md, samples/sample-codebuild-vpc/README.md, samples/sample-codebuild-vpc/buildspec.yml, samples/sample-codebuild-vpc/params/global.yml, samples/sample-codebuild-vpc/template.yml, samples/sample-codebuild-vpc/testspec.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/example-global-iam.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_stacks.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/schema_validation.py
To add support for build/deploy steps that use CodeBuild and need to connect to internal resources that are only available through a VPC.
This feature allows you to configure which VPC to connect to, using a specific list of subnets and security groups. The latter helps ensure that the connection is only allowed to connect when a specific security group is used.
Added three properties to the CodeBuild provider:
- vpc_id (string)
- subnet_ids (list of ids (strings))
- security_group_ids (list of ids (strings))
When you configure a pipeline to use a specific VPC, you need to specify the subnets to use as well.
In case you don't specify any security groups, they will be automatically created for you. These security groups allow all egress traffic by default. It is recommended to use a …
=> Add support for the CodeBuild provider to run inside a VPC

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
**Why?**
The Organization Identifier is referenced as `OrganizationId` in all ADF's CloudFormation stacks. With the exception of the pipeline management stack. In the pipeline management stack, it was referred to as `OrganizationID`. This made it impossible to share logic from other stacks or rely on the standard way of writing Id.
**What?**
Changes `OrganizationID` to `OrganizationId`.
---
=> Make organizationId consistent with other Id vars in pipeline management

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
**Why?**
1. With a recent PR, an attempt was made to restrict the `iam:PassRole` permissions for the pipeline generator. However, since ADF supports configuring which role to use, this would introduce a breaking change.
2. The policy in the pipeline management attached to the CloudFormation role does not allow it to `DeleteStack` or `UpdateTerminationProtection.` As those were using the RequestTag condition that is not compatible with these API calls.
3. Additionally, the `iam:TagResource` action does not exist.
**What?**
1. Reverting to the previous policy of `iam:PassRole`. Plan is to address this in the next major ADF release.
2. For the `DeleteStack` and `UpdateTerminationProtection` actions, it is updated to use the `iam:ResourceTag` condition instead.
3. While the `iam:TagResource` …
=> Fix pipeline generation policies

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/create_repository.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/repo.py
When a CodeCommit repository was supposed to be created, it would fail with the following error message:
> An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::111111111111:assumed-role/adf-global-base-deploymen-CreateRepositoryLambdaRo-GP8W3IRDCGY2/ADFPipelineCreateRepositoryFunction is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::111111111111:role/adf-automation-role
> Traceback (most recent call last):
>   File "/var/task/create_repository.py", line 48, in lambda_handler
>     repo = Repo(
>   File "/opt/python/repo.py", line 36, in __init__
>     self.session = sts.assume_cross_account_role(
>   File "/opt/python/sts.py", line 24, in assume_cross_account_role
>     sts_response = self.client.assume_role(
>   File …
=> Fix repository creation permission in pipeline management

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/identify_out_of_date_pipelines.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
Two blockers with the stale pipeline deletion process:
1. Fix iterating over pipelines that need to be deleted:
**Why?**
At the moment, the input of the State Machine invocation that is handling
delete operations is unwrapping the `pipelines_to_be_deleted` from the input.
While the pipeline deletion State Machine also tries to do that.
**What?**
Iterating over the input elements directly instead in the pipeline deletion
State Machine.
2. Delete pipeline regions SSM Parameters after successful CloudFormation delete stack operation:
**Why?**
At the moment, when it determines which pipelines need to be deleted, it will
also delete the parameters.
However, if the deletion fails, the parameters have been deleted and it will
not be able to detect that the stack needs to be deleted still. …
=> Fix stale pipeline deletion

src/lambda_codebase/account_processing/process_account_files.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/process_deployment_map.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/sync_to_s3.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/tests/test_sync_to_s3.py, src/template.yml
This PR implements steps 2 to 4 of issue #518. Since all these code changes are related, I put them in one PR:
1. Forward CodePipeline Execution Id to Account Mgmt Creation SFN
Step 2 of fixing #518.
**Why?**
As explained in #518, we need to forward the execution id of the CodePipeline
that triggered the Account Management state machine so we can wait for to
complete.
**What?**
Adding the CodePipeline execution identifier to the Step Functions
State Machine invocation to enable tracing state machines in progress at
CodeBuild execution time.
2. Only process account and deployment maps generated by same ADF version
**Why?**
When an account file or deployment map is updated, it should only be processed
when the version equals the current ADF version. Otherwise it should skip the
file.
This …
=> Fix account creation wait for bootstrap to complete

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/tests/test_initial_commit.py, src/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/tests/test_initial_commit.py
There were two issues with the previous implementation:
1. Fix detecting changes upon update properly
**Why?**
CodeCommit has a limit of 100 files per commit.
To workaround this limit, the implementation walked across all the files
and split it into chunks of 99 files. However, when one of those chunks would
not have any changes, it would raise an exception that was handled at the
incorrect level. Causing it to abort the creation of the PR all together.
Even when there were changes in another chunk.
**What?**
Fixed handling the "no changes in this chunk" error at the chunk level.
So it will only skip that chunk and continue with the next.
Maintaining a list of commits that were created, and if any were, it will open
the pull request.
Additionally, the initial commit code had a lot of …
=> Fix initial commit implementation

src/template.yml
When you move an account from the root to an organization unit (OU), an event is emitted that should trigger the Account Bootstrap state machine.
However, the task role that was configured did not have the necessary permissions to invoke the state machine.
A new role is created that will enable the event to trigger the Account Bootstrap state machine.
While investigating the issue, it was also noticed that the original task role had permissions that were no longer required. Those stale permissions are removed too.
---
=> Fix account bootstrap on OU move

src/lambda_codebase/account_bootstrap.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/errors.py, src/template.yml
Issue: #519.
When an account is created, the API call will return but behind the scenes the process to provision the account fully is still in progress.
When the account bootstrap process tries to on-board one of these newly created accounts, it will fail with a `SubscriptionRequiredException` being thrown.
This will cause the account bootstrap process to fail.
Introducing a new error class: `AccountCreationNotFinishedError`. This is added to explain what the `SubscriptionRequiredException` implies.
The Step Function that performs the Account Bootstrap process will catch the error and retry several times with a longer duration in between intervals to ensure the system has sufficient time to create the account.
Plus one minor change to the `main.py` wait for state machine message.
---
By …
=> Add account creation in progress retry logic

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/initial_commit.py
When the repository is created, there are no commits in the repository yet. The process tried to create a branch where the parent commit id was empty. This is not allowed.
Instead, it should only create the branch when there is a commit to branch off from. Otherwise it should only create the new commits on the main branch directly.
---
=> Fix initial commit on fresh install

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py, src/template.yml
Bootstrapping the deployment account can take long. After which it runs out of time in the Lambda function that is creating the bootstrap stacks failing the state machine execution.
Added retry logic to the state machine invoking the `CrossAccountExecuteFunction` Lambda.
Increased timeout for the `CrossAccountExecuteFunction` Lambda function and its invocation step in the state machine to 900 seconds.
Upon a retry, it needs to be able to recover and continue gracefully. Hence a waiter is added to wait for the current in progress execution until that is finished before attempting to create/update it again.
---
=> Add retries to account bootstrap process

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/store_config.py, src/template.yml
After deploying ADF for the first time, it will need to store the `adfconfig.yml` values in the AWS Systems Manager Parameter Store. Such that the logic inside the account bootstrap and account management state machines can execute correctly.
At the moment, the config is written after the Step Functions are triggered by syncing account configurations to S3. This will fail on the read of the `config` parameter.
Adding another step that will only store the configuration values in the ADF Bootstrap CodeBuild execution. Before it copies the files that would trigger the account management and account bootstrapping state machines.
---
=> Fix store ADF config before it needs to be read the first time

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/describe_codepipeline_trigger.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/sync_to_s3.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/tests/test_sync_to_s3.py
As described in issue #549. When an account is moved in or out of an organization unit (OU), the pipelines that include that OU are not updated accordingly.
By checking the type of trigger that started this CodePipeline execution, it will force the upload process of the deployment map files when the pipeline was triggered using a StartPipelineExecution API Call. As these are used when the pipeline is instructed to start by a Lambda function that detected an organization unit change.
* Add support for --force to the `sync_to_s3.py` helper.
* Add `describe_codepipeline_trigger.py` helper to fetch the trigger type of a specific execution.
* Set the `--force` as `$EXTRA_OPTS` that are passed to the `sync_to_s3.py` helper if needed.
* Allow `aws-deployment-framework-pipelines` CodeBuild …
=> Trigger pipeline regeneration upon organization changes

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/process_deployment_map.py
At the moment, when a pipeline definition is created or updated, a Lambda function triggers the pipeline generation state machine.
While triggering this state machine, it does not specify a name for the execution. So Step Function will generate its own unique name instead.
However, when you look at the pipeline generation state machine, it is impossible to tell which generation is running or has failed from the list of executions. As all executions have unique ids.
Changed the start execution process when a pipeline is created or updated, such that it will include the pipeline name at the start of the execution.
Followed by the CodePipeline execution id of the `aws-deployment-framework-pipelines` process that created or modified the deployment map that contained this pipeline.
As well as …
=> Fix readability of pipeline generation executions by Step Functions

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/create_or_update_rule.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/base_resolver.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/generate_pipeline_inputs.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_params.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cache.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/deployment_map.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/pipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_cache.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver_param_store.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver_stack_output.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver_upload.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/account_name1_eu-central-1.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/parameter_environment_acceptance_tag_project_a.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/parameter_environment_prod.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/parameter_extra_one_only.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_cfn_global.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/stub_cfn_global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/tag_cost_center_free_only.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/tag_cost_center_nonfree_only.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/tag_department_alpha_only.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/stubs/tag_geo_eu_only.json, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_generate_params.py
The `generate_params.py` script relied on the `account_ous.json` file that was uploaded to the shared modules bucket.
While ADF got support for newer account target selection mechanisms, the `account_ous.json` file structure was not updated accordingly.
To ensure future support and ease to maintain new account target selections it was decided to drop the `account_ous.json` and move to the pipeline input definition instead.
* Updated generate_params.py to rely on the pipeline input definition instead.
* Updated generate_params.py to ensure that parameters would be generated correctly. Refactored it, as before it was using a complex structure inside the resolver class. With the new changes, it relies on generating a new copy of the parameters with each step instead. Making it easier to test …
=> Fix generate_params.py to rely on pipeline input definitions instead

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
For source providers like `codestar`, it does not require an account id to be configured for the source account. When that is missing, the current code crashes while generating the CodePipeline stack.
Changed the account_id lookup to support missing values.
---
=> Fix CodePipeline source account id lookup to support missing key

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
At the moment, the IAM policy was allowing `iam:CreateRolePolicy`. This action does not exist.
Changing it to: `iam:AttachRolePolicy` and changing order to be alphabetically.
---
=> Fix AttachRolePolicy on automation roles

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
The identify-out-of-date-pipelines process will iterate over the S3 files and delete the stale pipelines that are no longer defined.
However, if you delete a deployment map file, the old deployment map would still exist in the pipelines bucket. Which will put the identify-out-of-date-pipeline process in the wrong direction, as it will think that these pipelines are still active.
Instructing the sync to S3 process to delete stale files in the S3 bucket, so deleted deployment map files are also deleted in the pipeline bucket.
---
=> Add clean-up of stale deployment map files in the pipeline bucket

docs/providers-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/generate_pipeline_inputs.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/identify_out_of_date_pipelines.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/schema_validation.py
The CodeStar provider did not support the `CODEBUILD_CLONE_REF` artifact mode yet. This is useful if you would like to access the git repository, for example to analyze the history or checkout a different branch.
For CodeStar Connections, it was trying to resolve the CodeStar Connection Arn from SSM Parameter Store at the pipeline stack generation. However, resolving parameters should be performed in the input generation step.
* Added support to define the `output_artifact_format` in the CodeStar source provider. Allowing `CODEBUILD_CLONE_REF` to be defined as the output format.
* Moved resolving the `codestar_connection_path` in SSM Parameter Store to the pipeline input generation. As this is where it should be performed. The Lambda function resolving these parameters has the required …
=> Add support for CodeStar CodeBuild clone ref and update CodeStar setup

docs/providers-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/schema_validation.py
Allowing a specific parameter file to be used. This is especially useful if you
would like to reuse a template. Often these templates are committed or generated
with another generator than `generate_params.py`.
* Added `params_filename` to the CloudFormation provider schema.
* Updated the CloudFormation provider to support setting the `params_filename`.
* Documented the `param_filename` property in the CloudFormation provider docs.
Additionally, I refactored the `adf_codepipeline.py` file. As this file was not following
the line length requirements. When the line length was updated before, the resulting
code was hardly readable.
After this change, I realized a number of the properties were not configured correctly.
It would use the default_provider configuration first, and when that was …
=> Feat: Allow param filename configuration per target with the CFn provider + bugfixes

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
When CloudFormation tries to update a pipeline notification topic, it will perform a list operation on the subscriptions for that topic. This action requires `sns:ListSubscriptionsByTopic` permissions which is not granted yet.
Added that permissions so it can update the notification topic when required.
---
=> Fix CloudFormation pipeline notification topic permissions

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
The CloudFormation role that is used to deploy the pipelines was only allowing CodeBuild projects which name started with `adf-build-`. However, it should also allow `adf-deploy-` resources, as that is how the CodeBuild project is named when it is used as a deployment provider.
Added the `adf-deploy-*` project name for CodeBuild projects deployed by the pipeline generation process.
---
=> Fix permissions to allow CodeBuild as a deployment provider

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml
With the move to Step Functions, the majority of the workload for the adf-pipelines CodeBuild process was moved to the ADF Pipeline Management State Machine in AWS Step Functions.
However, the policies attached to the original CodeBuild environment were not updated yet. Additionally, the machine type used for this process could be reduced in size too.
* Changed the name from `pipeline-provisioner*` to `pipeline-generation-provisioner*`, as it no longer privisions the pipelines but ensures the Step Function has the required input to do it instead.
* Removed the original provisioner role from AssumeRole permissions that it no longer requires.
* Removed environment variables that are not used by the process to provision the pipeline generator.
* Removed policy statements that the …
=> Improve adf-pipelines CodeBuild permissions kickstarting SFN

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/example-global-iam.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/example-global-iam.yml
With the current names defined in the example-global-iam.yml files, they would clash with the ADF policies defined on these roles.
* Add `custom-` prefix to the policy name so they are unique. This makes it easier to understand where policies are defined.
---
=> Use unique policy names in adf-bootstrap example global-iam.yml files

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
There is a typo in the pipeline management resource names. This PR fixes that.
Instead of `Mangement` it should be `Management`.
---
=> Fix pipeline management logical id typo

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py
The CodeBuild class had similar issues as the CodePipeline class where the line length requirement was not met. Plus code readability was not terrific either.
Fixed the readability by properly breaking the lines. Another pass of refactoring code too.
I don't like the large if / else in the constructor + large code overlap between the two branches. This requires more refactoring later.
---
=> Chore: Refactor CodeBuild readability

docs/admin-guide.md
The update and troubleshooting steps did not reflect the recent changes introduced with the refactoring of the account and pipeline management to rely on AWS Step Functions.
* Updated the admin docs to include the update and troubleshooting steps of the new account and pipeline management state machines.
---
=> Document changes in ADF update process and troubleshooting steps

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py
With the `aws-deployment-framework-bootstrap` pipeline, it updates CloudFormation stacks in parallel to speed things up.
If, however, there is an error, it is hard to determine which account, region, and stack experienced an issue.
* Adds context information in the errors thrown, such that it is possible to debug the issue quickly.
* Fixed line length issues too.
---
=> Improve CloudFormation error reporting

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
Customers were seeing issues with throttling around CodeBuild APIs
Until we can replace it with a lambda based solution, we will have to retry. 
Introduced retry in the stepfunctions. 12 attempts, 150 seconds with a backoff factor of 1.05
---
=> Retrying RunCDK stage when CodeBuild throws an exception

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
The pipeline input generation would retry failures that would result in the same error.
For specific error classes thrown by this process, it should not attempt retries at all.
Albert Einstein:
> The definition of insanity is doing the same thing over and over
> and expecting different results.
* Abort retries if the error code is of these specific types.
---
=> Generating input should not retry upon specific errors

.github/workflows/mega-linter.yml
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: actions/upload-artifact@v2
- Bumped version of GH Action
---
=> Bumping upload-artifact to v3 (Node 12 -> 16)

.github/workflows/mega-linter.yml, .mega-linter.yml, linters/custom-adf-dict.txt
1. There is code in the GitHub workflow for MegaLinter to support submitting pull requests with linter fixes. We are not using this functionality (also it doesn't work through forks), hence removing that code. 
2. Some linters like `hadolint` and `eslint` support Sarif reporting. GitHub can display results from a third-party static analysis tool in your repository on GitHub. This requires results stored in a SARIF file that supports a specific subset of the SARIF 2.1.0 JSON schema for code scanning.
MegaLinter supports this for the linters that support it. Results will display in the repository on GitHub automatically and this is very useful, see the below example: 
- Cleaned up the MegaLinter GH Actions workflow
- Added Sarif support!
--- …
=> Adding SARIF report support

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_params.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/tests/test_generate_params.py
An error was generated when the `aws-deployment-framework-bootstrap` is mirrored from another location, via a pipeline that is deployed with ADF. For example, hosted in Github, where the pipeline connects to Github via a CodeStar Connection and pushes the code to the local CodeCommit repository.
In this case, the `generate_params.py` file will look for the new `pipeline_input` attribute in the pipeline definition. While the pipeline definition was generated with a previous version of ADF, thereby using the `input` attribute key instead.
Introduced backward compatibility to the `input` key if the `pipeline_input` key is missing in the pipeline definition.
Also added a comment that this support for backwards compatibility will be dropped in the next major release of ADF.
---
By submitting …
=> Fix bootstrap mirror pipelines

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_organizations.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/test_main.py
While running the `adf-build/main.py` script:
1. It would get the list of accounts of this specific AWS Organization.
2. Spin up a thread for any of the non-deployment accounts.
3. In the thread, check if the account is in the root or in a protected OU. If so, it would stop the thread. If not, it would deploy the bootstrap templates. So far so good.
4. When invoking the Step Function to enable the cross-account access, it would use the list of account ids it retrieved before. However, this list is unfiltered.
Therefore, the Step Function State Machine would try to enable the cross account access on accounts that were in the root and/or in protected organization units.
We would only need to bootstrap accounts that are:
* Active,
* Not in the AWS Organization root, and
* Not in an AWS …
=> Fix bootstrapping accounts in non-protected OUs only

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml, src/template.yml
Issue: #595
The management account alias cannot be configured by the account management state machine, as the cross account access role does not have enough permissions to create, list, or delete the aliases of the management account.
The cross-account access role that is deployed in the management account gets the required permissions.
These will only be applied if the management account is bootstrapped by ADF.
It assumes into the cross-account access role to list, create, and/or delete the account aliases. Hence, this change removes the permissions from the Lambda function role itself. As those are not used and would only apply to the deployment account.
---
redistribute this contribution, under the terms of …
=> Fix management account config alias through ADF account management

src/lambda_codebase/account_processing/process_account_files.py, src/lambda_codebase/account_processing/tests/test_account_file_processing.py
There is a bug, where if an account full name has white space in it, it will not trigger the relevant account management state machine. 
*Issue #, if available:* #597
Strip unsupported chars from the account name before starting a state machine execution. 
---
=> Sanitizing account names before using them in SFn Invocation

samples/sample-ec2-with-codedeploy/scripts/install-codedeploy.sh
**Why?**
At the moment, the install script for CodeDeploy would install CodeDeploy using the global S3 URL to fetch the file from the S3 bucket.
As such:
```
https://aws-codedeploy-${REGION}.s3.amazonaws.com/latest/install
```
However, the CodeDeploy Gov cloud buckets are not available through this global URL. So when the REGION=`us-gov-east-1` or `us-gov-west-1` it would fail.
Please note:
The gov-cloud buckets exist, as can be found here: https://docs.aws.amazon.com/codedeploy/latest/userguide/resource-kit.html#resource-kit-bucket-names
**What?**
To fix the install script, we should use the regional URL instead:
```
https://aws-codedeploy-${REGION}.s3.${REGION}.amazonaws.com/latest/install
```
--- …
=> Fix CodeDeploy sample to work in gov-cloud

src/template.yml
When uploading the deployment account bootstrap templates to S3 as part of the CodeBuild in the management account, `sam build` is run twice - once for `adf-bootstrap/deployment/pipeline_management.yml` and once for `adf-bootstrap/deployment/global.yml`. Running `sam build` outputs the packaged code and templates to `.aws-sam/`. However, running this a second time simply overwrites the code/templates in `.aws-sam/`
Therefore, the code/templates built by running `sam build -t adf-bootstrap/deployment/pipeline_management.yml` are never referenced, never uploaded to S3 and never deployed.
The `pipeline_management.yml` SAM application is actually included within the `global.yml`, so the build of this application is included in the SAM build for the `global.yml`. …
=> Remove Unused SAM Build

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py
This is the configuration in the deployment map file for custom pipeline:
```
params:
pipeline_type: "yourCustomTypeHere"
```
However, it was never loaded as it was getting an invalid property name so it always sets it to DEFAULT_PIPELINE
- Change `type` to `pipeline_type` as set in the deployment map
---
=> [Bug] Fix custom pipeline type configuration not loaded

docs/serverless-application-repo.md
SAR readme file has broken link to our old CI.
- Updated link to our GitHub build badge
---
=> Fixing broken Travis link (and build badge)

.mega-linter.yml
We have a linter failure in #619 because the latest MegaLinter release did not yet update CFN Lint. 
Temporarily disabling cfn-lint to un-block, I've created #629 for tracking
=> Temporarily disble cfn-lint for #619

.github/workflows/mega-linter.yml, .mega-linter.yml, .prettierrc.js
Upgrade megalinter to v7
Fixes #629 
Upgraded megalinter to v7 and remove misspell due to deprecation.
=> Upgrade megalinter to v7

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml, src/template.yml
**Why?**
The ADF Automation Role will need the CodeCommit:UntagResource permission when you change the tags that should be applied to a CodeCommit repository.
---
=> Fix resource untagging permissions

.github/workflows/mega-linter.yml, .mega-linter.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/regional.yml
2 linter errors emerged:
- New version of `cfn-lint` enforces the use of `UpdateReplacePolicy` / `DeletionPolicy`.
- e-mail address was missing a hyperlink. 
- Explicitly set the default `Delete` policy.
- Created hyperlinks for the e-mail address. 
- Explicitly set GH reporters, fixed a type in the linter yaml. 
---
=> Linter fixes

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
**Why?**
No access was provided to pipelines that rely on GitHub repositories as their source, using the GitHub OAuth token stored in the `/adf/github_token` secret in Secrets Manager.
This issue was introduced with the refactoring to the separate pipeline management stack in ADF v3.2.0.
**What?**
Added access rights for the pipeline creation stack to fetch the GitHub OAuth secret.
---
=> Fix GitHub Pipeline secret token usage

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_chatbot.py
The AWS Chatbot integration had an error that was introduced with the refactoring in v3.2.0 release. This prevented ChatBot configurations to be applied correctly.
Additionally, the pipeline creation process did not have the required permissions to manage the pipeline notifications yet.
Both issues are addressed in this change request.
---
=> Fix ChatBot channel ref + add notification management permissions

docs/admin-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/example-global-iam.yml
There are a few requirements to adopt CodeStar connections that were not documented yet. This change request addresses those and introduces the required policy as an example in the example-global-iam.yml template.
CodeStar Connections are the preferred method to link with GitHub nowadays. Hence, updated the admin guide to highlight this preference.
---
=> Improve docs and add CodeStar Connection policy

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
Following security best practices and fixing things Aquasec/Cloudsploit is complaining about!
- Reduced trust policy to only states services as it's only passed to a state machine
- Reduced permissions to only invoke Lambda and publish SNS with only the resources that it uses 
---
=> Limit adf-state-machine-role to what is needed

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py
By default Python's `json.dumps` adds a space after `,` and `:` characters. This commit removes those spaces so they don't count against SCP policy limits.
=> Upload SCP policies with spaces removed

src/template.yml
The adf-codecommit-role-base role from the ADF CloudFormation Initial Base Stack for the Management Account in the us-east-1 region, with the trust policy being assumable from `codecommit.amazonaws.com` doesn't seem be used anywhere. I couldn't find it being used in ADF codebase, or the cloudformation template it comes in. I couldn't anything find you could do with codecommit that requires a role with `codecommit.amazonaws.com` being the trusted service principal to assume to it or even passing a role to codecommit.
In the organisation that I'm working with ADF deployed, this role doesn't seem to be ever used as well.
With that in mind I'm proposing to delete this role as it doesn't seem to be used.
Describe why you are proposing these changes
Description of …
=> Remove CodeCommitRole from initial base stack

.mega-linter.yml, .prettierrc.js, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/template.yml
According to the S3 docs [0], it is recommended to enforce the bucket ownership via the Ownership Controls.
1. Upgraded the enforce bucket ownership from the ACL (AccessControl) to OwnershipControls.
2. Fixed MegaLinter to use Prettier with the multiline-arrays plugin.
---
* [0] https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-policy-alternatives-guidelines.html
---
=> Move from ACL enforced bucket ownership to Ownership Controls + megalinter prettier fix

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/terraform/adf_terraform.sh
Account based variables are not copied to the temporary directory that holds all terraform files. Without this fix, ADF executions fail with 
```sh
cp: cannot stat '/codebuild/output/src4248460905/src/tfvars/111111111111/*': No such file or directory
```
See #664 for a more detailed description.
#664 
- Use `/.` (works) instead of `/*` (fails) to copy all contents of a directory
---
=> fix: :bug: copy account based variables correctly

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py
ADF fails to build in the bootstrap pipeline if no `allow-empty-targets` value is configured in the `adfconfig.yml` file.
Root cause, the default value is a boolean False. While the Parameter Store service expects values to be of type string.
This change set fixes it by converting the default to string when written to Parameter Store.
---
=> Fix initial value type of allow-empty-targets

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml
The pipeline management Step Function state machine is not a valid definition.
The error(s) it catches should be an array.
---
=> Fix pipeline management state machine error handling

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/initial_commit.py
In case a previous deployment of ADF failed for whatever reason, running it again would require you to delete the branch it created the first time.
Since we don't want to end up deleting a branch that we did not create, the proposed solution is to generate a unique name for the branch and use that.
1. It will start with the version number as the branch name, like `v3.2.0`.
2. If that exists, it will iterate from `v3.2.0-no-1` to `v3.2.0-no-9`.
3. Highly unlikely, but if all of these exist, it will fallback to `v3.2.0-at-{unix_timestamp}`.
---
=> Auto generate unique branch names on new version deployments

.cfnlintrc, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/pipeline_management.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/regional.yml, src/template.yml
At the moment, if there is an `AccessControl` set on the S3 Bucket (in v3.2.0 ADF had this set), you cannot remove it and move to the new Bucket Ownership Rules.
The only option to move to the new Bucket Ownership Rules would be to add those and remove the `AccessControl` property after. However, since we need to allow customers to upgrade, we cannot do this in a single release.
Added the Bucket Ownership Rules today, and keep the `AccessControl` for now.
We can remove the `AccessControl` property in a future version. While we instruct customers to first upgrade to v4.0.0 if they need to move to the version where this property is removed.
---
=> Add AccessControl on S3 Buckets

docs/user-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/terraform/adf_terraform.sh
The current solution doesn't support different variable values per region in an account.
*Issue #661 
- adf_terraform.sh, added the region folder management
- docs/user-guide.md, added documentation regarding the new feature
---
=> Feat: added support for distinct variable files per region per account in terraform pipelines

docs/providers-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codepipeline.py
Wanted to set kms_encryption_key_arn but it wasn't available. So decided add the two missing useful properties.
- Add kms_encryption_key_arn and cache_control parameters for s3 deploy provider
---
=> Add kms_encryption_key_arn and cache_control parameters for s3 deploy

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml
To allow the deletion of the Default VPC if one were to manage the management account via ADF's Account Management (adf-accounts).
Added the missing permissions to delete and describe the default VPCs in the management account.
---
=> Add delete default VPC in management account support

src/template.yml
When ADF needs to tag or untag the cross-account access role, it fails to do so.
* Granting the required permissions to tag and untag the roles.
* Removal of the invalid `s3:ListObjects` permission, the permissions required to list objects in a bucket are managed via the `s3:ListBucket` permission. Which is already present.
---
=> Fix tagging of Cross Account Access role in the management account

.github/workflows/adf.yml, .github/workflows/mega-linter.yml
Keeping up to date with the latest GH Actions workflows.
*Issue #, if available:* #698
actions/checkout v3→ [Updated: v4]
actions/upload-artifact v3→ [Updated: v4]
github/codeql-action v2→ [Updated: v3]
actions/setup-python v4 → [Updated: v5]
---
=> Version bumping GH actions

src/lambda_codebase/event.py
When you attempt to install ADF the first time, it will bootstrap the deployment account via the account bootstrap state machine. This, however, happens just before executing the bootstrap pipeline the first time. Resulting in missing parameters in the deployment account at the time the [regional stack](https://github.com/awslabs/aws-deployment-framework/blob/7a4359fcc441f3e62818b3c24569ddf069ec7a74/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/regional.yml#L14) is deployed.
This stack requires the `extensions/terraform/enabled` parameter (see [here](https://github.com/awslabs/aws-deployment-framework/blob/7a4359fcc441f3e62818b3c24569ddf069ec7a74/src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/regional.yml#L14)). If that …
=> Fix clean bootstrap of the deployment account

Makefile, docs/installation-guide.md
When running the make / install process of ADF, we need to ensure it will not continue if some of the tools are not installed yet.
For example, in the past, if you did not install jq, it would still continue with the build process. Resulting in a broken template at deployment time.
As reported in #696, the Python version in the environment was set to v3.8, which resulted in a broken installation process too.
* Updated the documentation to indicate that `jq` needs to be available too.
* Added checks in the build process to exit and warn the user about missing dependencies.
---
=> Install: Add checks to ensure installer dependencies are available

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/initial_commit/initial_commit.py, src/lambda_codebase/initial_commit/initial_commit.py
We are using aws-deployment-framework for deployments. In our AWS accounts we are solving an Security Hub findings.
One of the finding found is referenced as CWE-20,79,80 - Cross-site scripting(XSS) with  high security labelled.
The issue is in the Jinja2 library, as used by `initial_commit.py` files. There was no `autoescape=True`.
I added the `autoescape=True` attribute to resolve this.
With these changes, the finding related with XSS is resolved in our AWS account.
Please consider this in next release.
Security-hub finding issue -CWE-20,79,80 - Cross-site scripting
> User-controllable input must be sanitized before it's included in output used to dynamically generate a web page.
> Unsanitized user input can introduce cross-side scripting (XSS) vulnerabilities that can lead to …
=> Fix Jinja2 template rendering with autoescape enabled

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/requirements.txt, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/requirements.txt
With the current dependency requirements, a build pipeline will fail to install liburl3 if a Python version prior to v3.10 is used.
As botocore defined a Python version specific requirement for urllib3, as can be seen at https://github.com/boto/botocore/blob/1.34.17/setup.py#L28-L29.
If urllib3 is installed in a CodeBuild container which has Python version < v3.10, we should use the latest 1.26 release that is available instead.
---
=> Fix pipeline support for CodeBuild containers with Python < v3.10

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/parameter_store.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/stubs/stub_cloudformation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_cloudformation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_parameter_store.py, src/template.yml
Initially, ADF would generate bootstrap stack names that included the name
of the OU at the end. For example, for an OU named banking, it would generate
the global `adf-global-base-banking` stack.
This, however, makes it harder to harden ADF. As it would need access rights
to deploy and manage CloudFormation stacks with a wildcard at the end.
Instead of listing a limited number of stack names.
Additionally, it makes it harder to write an SCP to limit who can update these
stacks as well.
It also makes it impossible to move an account from one OU to another, as the
previous bootstrap stack will contain resources that the new stack attempts
to create.
* Instead of using the OU name, the bootstrap stacks will be named:
`adf-(global|regional)-base-bootstrap`.
* Exception being the …
=> Feat static bootstrap stack names

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/generate_params.py
When using ADF in a multi-org setup the generate_params.py helper file will read local Org Stage specific config files. 
If however the environment variable ADF_ORG_STAGE is not set in the Codebuild environment, the generate_params.py should not default to 'Dev' org. 
This can result in loading the incorrect Local Params file when deploying into a non 'Dev' Stage.
Remove Default value in helper file.
- Just updated the generate_params.py
---
=> fix: remove dangerous default ADF_ORG_STAGE

samples/sample-expunge-vpc/src/lambda_vpc/lambda_function.py, samples/sample-expunge-vpc/src/lambda_vpc/requirements.txt, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/iam_cfn_deploy_role_policy.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/identify_out_of_date_pipelines.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/lambda_codebase/pipeline_management/process_deployment_map.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cloudformation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/list_utils.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/organizations.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/resolver.py
Amazon CodeGuru suggested improvements to:
* Use paginators in the sample-expunge-vpc code, after reviewing, this sample required some more attention.
* Change `if len(...) > or ==` statements to match against the value. A list with elements is True, an empty list is False. Improving readability.
* Move boto3 client and resource creation to the initialization phase of the process deployment map Lambda function, to speed up its execution in consecutive runs.
---
=> Fix sample expunge VPC, if-len, and process deployment maps

.github/workflows/mega-linter.yml
With the release of MegaLinter v7.11, the markdown-link-check dependency was upgraded to v3.12.1. This, however, fails checks where anchor links are used.
Fixed the MegaLinter workflow to v7.10 for now.
We can revert this change/loosen the requirement to v7 when the issue is resolved later on.
---
=> Fix Markdown Anchor Link Check

docs/admin-guide.md, docs/multi-organization-guide.md, src/lambda_codebase/initial_commit/adfconfig.yml.j2, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/target.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_target.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/stubs/stub_adfconfig.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/test_main.py
Since the `allow-empty-targets` configuration has not been part of an ADF release yet. We should use this opportunity to make sure that the configuration values it uses match the style of the other variables.
Changed it to match `enabled` and `disabled` as used elsewhere.
---
=> Fix allow-empty-targets to match config boolean style

.github/workflows/adf.yml, Makefile
When you clone the ADF Github repository, it will not fetch the git tags. The installation docs describe that you should run `git fetch --tags` to retrieve those. However, if someone forgets to run that command, you run into a weird error that does not describe what is going wrong in a resolvable manner:
> Error: Failed to create changeset for the stack: aws-deployment-framework,
> Parameter validation failed:
> Invalid length for parameter Tags[0].Value, value: 0, valid min length: 1
Additionally, if you installed ADF with the updated installer before. Then forget to fetch the latest git tags when you are about to deploy a new version of ADF, it will return a version number that is based on the old version instead of the new one. Making it hard to determine what version of ADF was …
=> Install: Add version checks and pre-deploy warnings

CHANGELOG.md, docs/providers-guide.md, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_codebuild.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/tests/test_adf_codebuild_determine_build_image.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_default_pipeline_type.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_stacks/tests/test_pipeline_creation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/schema_validation.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/stubs/stub_deployment_map.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_deployment_map.py
Closes: #626
In prior versions of ADF, the CodeBuild image default was set to `UBUNTU_14_04_PYTHON_3_7_1`. This container image was no longer supported by the AWS CodeBuild service. Hence, using this version introduces a security risk as it is no longer patched.
Moving to the latest CodeBuild image `STANDARD_7_0` was proposed when we switched to CDK v2. This change of the default image to use was one of the main reasons why just upgrading to CDK v2 required a major version release. As updating the default introduces a breaking change that might impact the pipelines of ADF.
In the future, if we would only update the default we would require a new major version upgrade when `STANDARD_7_0` is deprecated too. Instead, this change proposes to require the image for the CodeBuild provider in the …
=> Require CodeBuild image from v4 onward

docs/admin-guide.md
As raised by issue #615, the old guide described that one could create a copy of the global.yml file into another child OU folder.
However, copies of the global.yml file are not updated by ADF automatically.
Instead, the user should use the `global-iam.yml` file. Such that the `adf-bootstrap/global.yml` is applied in all OUs except the deployment OU. Resolves #615.
---
=> Doc: Explain special purpose of adf-bootstrap/global.yml

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/cdk/cdk_constructs/adf_events.py
Resolves: #654.
The description of the pipeline completion triggers did not parse the dynamic parameters that were defined.
---
=> Fix pipeline completion trigger description

Makefile
In case one were to checkout a tagged release, then make changes, ADF will receive the tagged release number. Instead of tracking the change that was made in the release number as well.
By preventing these uncommitted changes, it makes it easier to detect what code is running in a specific version of ADF. So in case someone were to report an issue we can assume the number indicates which version of the code failed.
* Added check for uncommitted changes, these include files that are tracked by the git repository.
* Added check for newly created files, these would not be tracked by git yet.
---
=> Install: Add uncommitted changes check

src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/helpers/terraform/adf_terraform.sh
Fix terraform pipeline issues after upgrade to 4.0.0. Terraform is not able to upload tf statefile to S3 bucket due to wrong definition of S3 terraform backend
Issue #744, #745 
Added encryption properties to terraform S3 backend.
Added permission to codebuild role in the deployment account to read AWS Organizations api
---
=> Fix Terraform pipeline issue after upgrade to 4.0.0

src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/cache.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/parameter_store.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/target.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_cache.py, src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/shared/python/tests/test_parameter_store.py
Fixes: #781
When generating the pipeline definition, it needs to know whether or not empty targets are allowed, a config that is managed from the adfconfig.yml. To support this, the Target instances fetch the configuration value from parameter store.
When hundreds of targets are initialized, it will attempt to fetch this parameter way too often. Especially considering the value is not likely to change.
Apply caching on the fetch, put, delete operations in the Parameter Store class. Such that all ADF components that need to perform lookups frequently can benefit from this enhancement.
---
=> Apply caching when handling parameters

.github/workflows/mega-linter.yml, docs/installation-guide.md, samples/sample-service-catalog-product/productX/template.yml
Recently our linters started failing to validate links to gnu.org. So I 
- Disabled the linkchecker for these domains
- Upgraded our linter
- Fix an issue with CFN lint expection and AMI ID, even though https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloud9-environmentec2.html#cfn-cloud9-environmentec2-imageid accepts an alias.
---
=> Linter upgrade and fixes

docs/admin-guide.md, src/lambda_codebase/initial_commit/adfconfig.yml.j2, src/template.yml
The bootstrap pipeline runs unit tests on ADF every time it is triggered. This implies the download of the development packages and the whole test suite to run, from my measurements, this adds 5-6 minutes to the overall execution time.
The current PR introduces a parameter in `adfconfig.yml`that disables the tests. If the parameter is not present, the tests are disabled by default.
- Added lookup of the parameter `config.run-tests` in `adfconfig.yml`
- Split the python packages installation in runtime packages and dev packages
- put dev packages installation and test under the condition that `run-tests` = `enabled`
- Added the default parameter in adfconfig.yml.j2
---
redistribute this …
=> Feature disable tests

samples/sample-cdk-app/.gitignore, samples/sample-cdk-app/package-lock.json, samples/sample-cdk-app/package.json, samples/sample-fargate-node-app/package-lock.json, samples/sample-fargate-node-app/package.json, samples/sample-terraform/tf/main.tf
To enable end-users to copy the samples with up-to-date dependencies.
* Added package-lock.json and removed it from .gitignore in sample folder; in case one would copy the sample as is and commit it to a new repository, it would ignore the package-lock.json file. It is generally recommended to commit this file to ensure dependency versions consistently use the same version as described in the package-lock file.
* Updated the dependencies for Node samples.
* Updated the Terraform version of the AWS backend.
---
=> Update sample dependencies
