- .travis.yml
- README.md
- docs/admin-guide.md
- src/bootstrap_repository/adf-build/shared/python/codepipeline.py
- src/bootstrap_repository/adf-build/shared/python/tests/test_cloudformation.py
- src/bootstrap_repository/adf-build/shared/python/tests/test_codepipeline.py
- src/bootstrap_repository/adf-build/shared/python/tests/test_s3.py
- src/bootstrap_repository/deployment/lambda_codebase/update_pipelines.py
- tox.ini
travis is passing tox with initials tests in py36 and py37.
> Adding in Travis and ensuring it works as intended

- src/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
The following lines were missing from the Build section of the pipeline resource:
Actions:
- Name: Build
Added lines in and tested in my environment
> Corrected missing section in pipeline config

- src/bootstrap_repository/deployment/global.yml
- src/bootstrap_repository/deployment/regional.yml
Addresses concerns around #23 related to S3 Bucket Policy
> Updating S3 Bucket Policy to not allow S3:Put*

- src/pipelines_repository/adf-build/generate_params.py
fixing bug in handling resolving ssm parameters without a leading slash
> fixing bug in handling resolving ssm parameters without a leading slash

- src/initial/lambda_codebase/event.py
Fixing up naming in event.py to ensure deployment account deploys correctly from scratch
> fixing up naming in event.py

- samples/sample-cdk-app/buildspec.yml
- samples/sample-cdk-app/index.ts
- samples/sample-cdk-app/package.json
Updated example to work with CDK version 1.0.0
> Fixed cdk example to work with 1.0.0 of CDK

- docs/user-guide.md
*Issue #, if available:* Parameters anchor was broken
*Description of changes:* Updated the anchor pointing to the Parameters section
> Resolved broken anchor on Parameters

- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
*Issue #, if available:* 126
fixing bug in the J2 when using contains_transform and top_level_regions
> fixing bug in the J2 when using contains_transform and top_level_regions (#126)

- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/global.yml
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-buildonly.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-cloudformation.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-codedeploy.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-customdeploy.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-s3.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/cc-service-catalog.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/github-cloudformation.yml.j2
- src/lambda_codebase/initial_commit/bootstrap_repository/deployment/lambda_codebase/initial_commit/pipelines_repository/pipeline_types/s3-s3.yml.j2
Added Server-Side Encryption for all the SNS topics that are defined as part of ADF and the pipeline definitions.
> Added Server-Side Encryption (SSE) for all SNS topics

- docs/user-guide.md
Update the link to the "nested stacks" section.
> Update link to nested stacks

- src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
#221 
**Updated deployment/global.yml** 
Added permission 'cloudformation:UpdateTerminationProtection' to resource AdfAutomationRolePolicy
> Updating AdfAutomationRolePolicy

- src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/global.yml
> fix a tiny typo in comment

- docs/admin-guide.md
**Why?**
Added detailed steps to support the upgrade process and
ease the troubleshooting process when ADF failed to deploy.
Also added steps to check the currently installed version + how to check whether that is the latest version.
Both requested by #330.
> Add upgrade and version check instructions to admin docs

- src/template.yml
**Fixes 🐞**
* Fix use of the `resolve:` intrinsic function on the first parameter
in the parameter files, #336.
> Release v3.1.2

- src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/main.py
- src/lambda_codebase/initial_commit/bootstrap_repository/adf-build/tests/test_main.py
> Remove extra 'is a'

- src/account_processing.yml
#460 
- Fix resource reference to point to function instead of function role.
> fix: #460 fix resource reference in statemachine policy

- src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
#455 
Converted string to array
> fix: #455 string should be array

- src/account_processing.yml
- src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/global.yml
N/A
Fixing the yamllint findings that got merged in.
> Fix yamllint findings

- samples/sample-terraform/variables.tf
Describe why you are proposing these changes
Linting is currently failing for the master branch. 
- Added in types to TF variables as per the linter requirements. 
---
> Fix: MegaLint style error

- .github/ISSUE_TEMPLATE/bug-template.yaml
- .github/ISSUE_TEMPLATE/doc-template.yaml
- .github/ISSUE_TEMPLATE/feature-template.yaml
- src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/example-global-iam.yml
Issues, feature requests are inconsistent. Providing templates to the project users ensures consistency.
Added templates for
- 📕 Documentation Issue
- 🚀 Feature Request
- 🐛 Bug Report
---
> [feat] - GitHub issue templates

- src/lambda_codebase/initial_commit/bootstrap_repository/adf-bootstrap/deployment/example-global-iam.yml
The linter complained, lets resolve that.
---
> Fix indentation warning in deployment/example-global-iam.yml

- src/template.yml
Great news to anyone who is following the PRs on ADF.
We are almost there at v3.2.0!
This PR updates the version number to v3.2.0.
I will publish the release after this PR is approved and merged.
---
> Release v3.2.0

- docs/user-guide.md
Describe why you are proposing these changes: There was a documentation error for using custom codebuild image, the properties dictionary was missing from example yml and was confusing users to implement the custome codebild changes.
Documentation was changed 
---
> fix documentation error for codebuild custom image

- Makefile
The missing dependency breaks the installation process
*Issue #742 
Added 'packaging' module installation during build_deps phase.
---
> Added 'packaging' installation due to unresolved dependency issue, fixes #742

- samples/sample-fargate-node-app/package-lock.json
- samples/sample-fargate-node-app/package.json
Patch CVE-2024-45296 and version bump fargate node sample
> Patch CVE-2024-45296 and version bump fargate node sample
